GET https://api.twitch.tv/helix/clips?broadcaster_id=71092938&started_at=2021-04-15T18:26:11.350Z&ended_at=2021-04-22T18:26:11.350Z
Authorization: Bearer n3xp9poli0vnfra7txvssrv84a7lcq
Client-Id: <client-id>